spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: rkg7mnNhfyr
    driver-class-name: org.postgresql.Driver