DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE AUTHORS (
  ID   BIGINT PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE GENRES (
  ID   BIGINT PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE BOOKS (
  ID        BIGINT PRIMARY KEY,
  NAME      VARCHAR(255),
  GENRE_ID  BIGINT REFERENCES GENRES (ID),
  AUTHOR_ID BIGINT REFERENCES AUTHORS (ID) ON DELETE CASCADE
);

CREATE TABLE COMMENTS (
  ID      BIGINT PRIMARY KEY,
  TEXT    VARCHAR(255),
  BOOK_ID BIGINT REFERENCES BOOKS (ID)
);